site_name: Plataforma Cognitiva

theme:
  name: material
  language: pt-BR
  features:
    - navigation.expand

nav:
  - Guia de Implementação:
      - Overview: index.md
      - Arquitetura: implementation-guide/architecture.md
      - Deploy: implementation-guide/deployment.md
      - Custos: implementation-guide/cost.md
      - Considerações: implementation-guide/considerations.md
      - Recursos Adicionais: implementation-guide/additional-resources.md
      - Revisões: implementation-guide/revisions.md
      - Tutoriais:
          - "🎯 Trabalho Prático (Passo a Passo)": implementation-guide/tutorials/trabalho-pratico.md
          - "Como criar EC2 Ubuntu": implementation-guide/tutorials/criar-ec2.md
          - "Como criar RDS PostgreSQL com pgvector": implementation-guide/tutorials/criar-RDS.md
          - "Como criar Bucket S3": implementation-guide/tutorials/criar-bucket-s3.md
          - "Como criar site no S3": implementation-guide/tutorials/criar-site-s3.md
          - "Como conectar EC2 ao RDS": implementation-guide/tutorials/conectar-ec2-rds.md
  - "Plataformas e Níveis de Maturidade":
      - "Visão Geral": platforms-services/README.md
      - "Nivel 1 - Hardware e Infraestrutura": platforms-services/nivel_1.md
      - "Nivel 2 - Modelos e Serviços de ML": platforms-services/nivel_2.md
      - "Nivel 3 - Aplicações e Serviços de IA": platforms-services/nivel_3.md
